### ISSUE TITLE
mkdocs serve no longer works with mkdocs-markmap 

### ISSUE THREAD

**Issue by andynameistaken** [neatc0der/mkdocs-markmap#39]
Error log when `mkdocs-markmap` is enabled in `mkdocs.yml`:

```
❯ mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
ERROR    -  Error reading page 'index.md': extendMarkdown() missing 1 required positional argument: 'md_globals'
Traceback (most recent call last):
  File "/Users/andy/Devel/code-vault2/vaultenv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/mkdocs/__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 63, in serve
    config = builder()
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/mkdocs/structure/pages.py", line 171, in render
    md = markdown.Markdown(
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/markdown/core.py", line 96, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/Users/andy/Devel/code-vault2/vaultenv/lib/python3.9/site-packages/markdown/core.py", line 125, in registerExtensions
    ext.extendMarkdown(self)
TypeError: extendMarkdown() missing 1 required positional argument: 'md_globals'
```

**Comment by neatc0der** [comment]
I can reproduce the error It's an issue concerning `mkdocs` version 1.3+
